version: 0.2
phases:
  install:
    commands:
      - npm install -g forever
      - npm install -g mocha
      - npm install
  pre_build:
    commands:
      - echo Testing...
      - npm test
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
