#%RAML 1.0 Library

usage: Provides access to defined data types.
types:
  CommandOutput: !include ../dataTypes/commandOutput.raml
  Input: !include ../dataTypes/input.raml
  Message: !include ../dataTypes/message.raml
